<?php

namespace App\Modules\API\Services;

use App\Models\User;
use App\Modules\Members\Models\Member;
use App\Modules\Subscriptions\Services\SubscriptionService;
use Illuminate\Auth\Events\PasswordReset;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Events\Verified;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Str;
use Laravel\Sanctum\NewAccessToken;

class AuthenticationService
{
    public function __construct(
        protected SubscriptionService $subscriptionService,
    ) {}

    /**
     * Register a new user.
     */
    public function register(array $data): User
    {
        return DB::transaction(function () use ($data) {
            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'phone' => $data['phone'] ?? null,
                'password' => Hash::make($data['password']),
                'admission_number' => $data['admission_number'] ?? null,
                'employee_id' => $data['employee_id'] ?? null,
                'department_id' => $data['department_id'] ?? null,
                'program_id' => $data['program_id'] ?? null,
                'academic_year' => $data['academic_year'] ?? null,
                'semester' => $data['semester'] ?? null,
                'is_active' => true,
                'notification_preferences' => [
                    'in_app' => true,
                    'email' => true,
                    'push' => true,
                    'sms' => false,
                ],
            ]);

            $user->assignRole($data['role'] ?? 'student');

            // Create associated member record (member_id auto-generated by boot method)
            Member::create([
                'user_id' => $user->id,
                'first_name' => explode(' ', $data['name'], 2)[0],
                'last_name' => explode(' ', $data['name'], 2)[1] ?? '',
                'email' => $data['email'],
                'phone' => $data['phone'] ?? null,
                'department_id' => $data['department_id'] ?? null,
                'program_id' => $data['program_id'] ?? null,
                'admission_number' => $data['admission_number'] ?? null,
                'membership_type' => $data['role'] ?? 'student',
                'status' => Member::STATUS_ACTIVE,
                'joined_at' => now(),
                'registered_by' => $user->id,
            ]);

            // Create trial subscription
            try {
                $this->subscriptionService->createTrialSubscription($user);
            } catch (\Throwable $e) {
                report($e);
            }

            // Fire registered event (triggers email verification notification)
            event(new Registered($user));

            return $user;
        });
    }

    /**
     * Create an access token for the user.
     * Enforces a concurrent session limit by revoking the oldest tokens.
     */
    public function createToken(User $user, ?string $deviceName = null): NewAccessToken
    {
        $maxSessions = (int) config('auth.max_concurrent_sessions', 5);

        // Revoke oldest tokens if user is at or over the limit
        $tokenCount = $user->tokens()->count();
        if ($tokenCount >= $maxSessions) {
            $tokensToRevoke = $tokenCount - $maxSessions + 1;
            $user->tokens()
                ->orderBy('created_at', 'asc')
                ->limit($tokensToRevoke)
                ->delete();
        }

        return $user->createToken($deviceName ?? 'mobile-api');
    }

    /**
     * Revoke the current access token.
     */
    public function revokeCurrentToken(User $user): void
    {
        $user->currentAccessToken()->delete();
    }

    /**
     * Revoke all tokens for the user.
     */
    public function revokeAllTokens(User $user): void
    {
        $user->tokens()->delete();
    }

    /**
     * Send password reset link.
     */
    public function sendPasswordResetLink(string $email): string
    {
        return Password::sendResetLink(['email' => $email]);
    }

    /**
     * Reset the user's password.
     */
    public function resetPassword(array $data): string
    {
        return Password::reset(
            $data,
            function (User $user, string $password) {
                $user->password = Hash::make($password);
                $user->setRememberToken(Str::random(60));
                $user->save();

                event(new PasswordReset($user));
            }
        );
    }

    /**
     * Change the authenticated user's password.
     */
    public function changePassword(User $user, string $currentPassword, string $newPassword): bool
    {
        if (! Hash::check($currentPassword, $user->password)) {
            return false;
        }

        $user->password = Hash::make($newPassword);
        $user->save();

        // Revoke other tokens except current
        $user->tokens()
            ->where('id', '!=', $user->currentAccessToken()->id)
            ->delete();

        return true;
    }

    /**
     * Verify email.
     */
    public function verifyEmail(User $user): bool
    {
        if ($user->hasVerifiedEmail()) {
            return true;
        }

        if ($user->markEmailAsVerified()) {
            event(new Verified($user));
        }

        return true;
    }

    /**
     * Resend email verification link.
     */
    public function resendVerification(User $user): void
    {
        $user->sendEmailVerificationNotification();
    }

    /**
     * Get the user's full profile data.
     */
    public function getProfile(User $user): User
    {
        return $user->load([
            'roles',
            'department',
            'program',
            'member.libraryCard',
            'activeSubscription.plan',
        ]);
    }
}
