<div class="min-h-screen flex items-center justify-center px-4 py-12">
    <div class="w-full max-w-md">
        <div class="text-center mb-8">
            <h1 class="text-2xl font-bold text-surface-900 dark:text-white">Document Verification</h1>
            <p class="text-sm text-surface-500 dark:text-surface-400 mt-1">Verify the authenticity of library documents</p>
        </div>

        <div class="card p-6">
            <form wire:submit="verify" class="space-y-4">
                <div>
                    <label class="label">Document ID</label>
                    <input type="text" wire:model="documentId" class="input-field w-full text-center font-mono text-lg"
                           placeholder="DOC-260522-XXXXXXXX" autofocus>
                    @error('documentId') <p class="text-sm text-accent-600 mt-1">{{ $message }}</p> @enderror
                </div>
                <button type="submit" class="btn-primary w-full justify-center" wire:loading.attr="disabled">
                    <span wire:loading.remove>Verify Document</span>
                    <span wire:loading>Verifying...</span>
                </button>
            </form>

            @if($searched)
                <div class="mt-6">
                    @if($notFound)
                        <div class="p-4 rounded-xl bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-center">
                            <svg class="w-12 h-12 mx-auto text-red-400 mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                            </svg>
                            <h3 class="text-lg font-semibold text-red-800 dark:text-red-300">Document Not Found</h3>
                            <p class="text-sm text-red-600 dark:text-red-400 mt-1">
                                The document ID "{{ $documentId }}" could not be verified. It may have been revoked or does not exist.
                            </p>
                        </div>
                    @else
                        <div class="p-4 rounded-xl bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 text-center">
                            <svg class="w-12 h-12 mx-auto text-emerald-400 mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            <h3 class="text-lg font-semibold text-emerald-800 dark:text-emerald-300">Document Verified</h3>
                            <div class="mt-3 text-left text-sm text-emerald-700 dark:text-emerald-400 space-y-1">
                                <p><strong>Document ID:</strong> {{ $document->document_id }}</p>
                                <p><strong>Title:</strong> {{ $document->title }}</p>
                                <p><strong>Type:</strong> {{ ucwords(str_replace('_', ' ', $document->type)) }}</p>
                                <p><strong>Generated:</strong> {{ $document->generated_at?->format('d M Y H:i:s') }}</p>
                                @if($document->generator)
                                    <p><strong>Generated By:</strong> {{ $document->generator->name }}</p>
                                @endif
                                <p><strong>Verifications:</strong> {{ $document->verification_count }} time(s)</p>
                                <p><strong>Status:</strong> <span class="text-emerald-600 font-semibold">Authentic</span></p>
                            </div>
                        </div>
                    @endif
                </div>
            @endif
        </div>

        <div class="mt-6 text-center">
            <a href="{{ url('/') }}" class="text-sm text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-300">
                &larr; Back to Home
            </a>
        </div>
    </div>
</div>
