@section('title', 'Reports')
<div class="space-y-6">
    <h1 class="text-2xl font-semibold text-gray-900 dark:text-white">Reports</h1>

    <div class="flex gap-2 border-b dark:border-gray-700 mb-4">
        <button wire:click="$set('activeTab', 'generate')"
                class="px-4 py-2 text-sm font-medium border-b-2 transition-colors
                {{ $activeTab === 'generate' ? 'border-primary-600 text-primary-600' : 'border-transparent text-gray-500 hover:text-gray-700' }}">
            Generate Report
        </button>
        <button wire:click="$set('activeTab', 'recent')"
                class="px-4 py-2 text-sm font-medium border-b-2 transition-colors
                {{ $activeTab === 'recent' ? 'border-primary-600 text-primary-600' : 'border-transparent text-gray-500 hover:text-gray-700' }}">
            Recent Reports
        </button>
    </div>

    @if($activeTab === 'generate')
        <div class="card p-6 space-y-4">
            <div>
                <label class="block text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Report Type</label>
                <select wire:model="selectedType" class="input-field w-full max-w-md">
                    @foreach($reportTypes as $key => $label)
                        <option value="{{ $key }}">{{ $label }}</option>
                    @endforeach
                </select>
            </div>

            <div>
                <label class="block text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Format</label>
                <select wire:model="format" class="input-field w-full max-w-xs">
                    <option value="pdf">PDF</option>
                    <option value="csv">CSV</option>
                </select>
            </div>

            <div>
                <label class="block text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Date From</label>
                <input type="date" wire:model="params.from" class="input-field w-full max-w-xs">
            </div>

            <div>
                <label class="block text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Date To</label>
                <input type="date" wire:model="params.to" class="input-field w-full max-w-xs">
            </div>

            <button wire:click="generate" class="btn-primary">Generate Report</button>

            @if($generatedReport)
                <div class="mt-6 p-4 bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 rounded-lg">
                    <p class="text-sm font-medium text-emerald-800 dark:text-emerald-300 mb-2">
                        {{ $generatedReport->name }} — {{ $generatedReport->generated_at?->format('d/m/Y H:i') }}
                    </p>
                    <button wire:click="download({{ $generatedReport->id }})" class="btn-primary text-sm">
                        <svg class="w-4 h-4 mr-2 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                        Download {{ strtoupper($generatedReport->file_type ?? 'pdf') }}
                    </button>
                </div>
            @endif
        </div>
    @else
        <div class="card overflow-hidden">
            <div class="overflow-x-auto table-mobile-cards">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="bg-gray-50 dark:bg-gray-800 text-left text-gray-500">
                                <th class="py-3 px-4">Name</th>
                                <th class="py-3 px-4">Type</th>
                                <th class="py-3 px-4">Generated By</th>
                                <th class="py-3 px-4">Date</th>
                                <th class="py-3 px-4">Status</th>
                                <th class="py-3 px-4"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($recentReports as $report)
                                <tr class="border-t dark:border-gray-700">
                                    <td class="py-3 px-4 text-gray-800 dark:text-gray-200">{{ $report->name }}</td>
                                    <td class="py-3 px-4"><span class="badge">{{ str_replace('_', ' ', $report->type) }}</span></td>
                                    <td class="py-3 px-4 text-gray-600">{{ $report->generator?->name ?? 'System' }}</td>
                                    <td class="py-3 px-4 text-gray-500">{{ $report->generated_at?->format('d/m/Y H:i') ?? '-' }}</td>
                                    <td class="py-3 px-4">
                                        <span class="badge {{ $report->status === 'completed' ? 'badge-success' : 'badge-warning' }}">{{ $report->status }}</span>
                                    </td>
                                    <td class="py-3 px-4">
                                        @if($report->file_path)
                                            <button wire:click="download({{ $report->id }})" class="text-primary-600 hover:text-primary-800 text-sm font-medium">
                                                Download
                                            </button>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr><td colspan="6" class="py-8 text-center text-gray-400">No reports generated yet</td></tr>
                            @endforelse
                        </tbody>
                    </table>
            </div>
        </div>
    @endif
</div>
